project:
  type: book
  output-dir: docs

book:
  title: "Big Data Programming for Data Scientists"
  author: "J. Hathaway"
  date: "1/12/2023"
  search: true
  repo-url: https://github.com/byuibigdata/bdbook
  repo-actions: [edit]
  repo-branch: master
  favicon: logo.png
  twitter-card: true
  site-url: https://byuibigdata.github.io/bdbook/
  output-file: "byui_big_data"
  downloads: [pdf]
  chapters:
    - index.qmd
    - intro.qmd
    - references.qmd

comments:
  hypothesis: true

bibliography: references.bib

format:
  html:
    theme: lumen

  # pdf:
  #   documentclass: scrreprt
  #   keep-tex: true


