project:
  type: book
  output-dir: docs

book:
  title: "Big Data Programming for Data Scientists"
  author: "J. Hathaway"
  date: "1/12/2023"
  search: true
  repo-url: https://github.com/byuibigdata/bdbook
  repo-actions: [edit]
  repo-branch: master
  favicon: logo.png
  twitter-card: true
  site-url: https://byuibigdata.github.io/bdbook/
  output-file: "byui_big_data"
  downloads: [pdf]
  chapters:
    - index.qmd
    - part: introduction.qmd
      chapters:
        - intro/bigdata.qmd
        - intro/tools.qmd
        - intro/projects.qmd
        - intro/rules_thumb.qmd
    - part: databricks.qmd
      chapters:
        - databricks/databricks_intro.qmd
        - databricks/community_edition.qmd
        - databricks/repo_navigation.qmd
    - part: spark.qmd
      chapters:
        - spark/spark_part_guide.qmd
        - spark/aggregations.qmd
        - spark/spark_intro.qmd
    - part: features.qmd
      chapters:
        - features/features_intro.qmd
    - part: docker.qmd
      chapters:
        - docker/docker_intro.qmd
    - part: training.qmd
      chapters:
        - training/training_intro.qmd

comments:
  hypothesis: true

bibliography: references.bib

format:
  html:
    theme: lumen
    code-line-numbers: true
    code-block-border-left: true
    code-block-border-bottom: false
    copy-images: yes
    copy-files:
      - "img/*"
      - "downloads/*"
    highlight-style: ayu
    toc-depth: 3

  # pdf:
  #   documentclass: scrreprt
  #   keep-tex: true
