# What is Databricks?

> For Data Science, Databricks Streamlines the end-to-end data science workflow — from data prep to modeling to sharing insights — with a collaborative and unified data science environment built on an open lakehouse foundation. Get quick access to clean and reliable data, preconfigured compute resources, IDE integration, multi-language support, and built-in advanced visualization tools for maximum flexibility for data analytics teams.   
> [Databricks website](https://www.databricks.com/product/data-science)

![Databricks comparison[^1]](../img/Marketecture-Spark-comp-page.png)

> With origins in academia and the open-source community, Databricks was founded in 2013 by the original creators of Apache Spark™, Delta Lake, and MLflow. As the world’s first and only lakehouse platform in the cloud, Databricks combines the best of data warehouses and data lakes to offer an open and unified platform for data and AI.   
> [Databricks website](https://databricks.com/company/about-us)

## The elevator pitches

> - [It's time for DataBricks!](https://youtu.be/_1QQHv7T9og)
> - [Databricks is the AI Company](https://youtu.be/1cJ0XYaARBY)
> - [Introduction to Databricks Unified Data Platform: 5 min demo](https://youtu.be/n-yt_3HvkOI)

## The details

### Clean and reliable data

### Preconfigured compute resources

### IDE integration

Databricks has taken the Jupyter Notebook (`.ipynb`) and the classic notebook interface and built a tool that is highly responsive and usable for data scientists and engineers.

### multi-language support


### built-in advanced visualization tools



[^1]: https://www.databricks.com/spark/comparing-databricks-to-apache-spark
